from enum  import Enum

class ProductErrorCode(Enum):
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    INVALID_PRODUCT_DATA = "INVALID_PRODUCT_DATA"

class FileErrorCode(Enum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"